development:
  sessions:
    default:
      database: mongoid
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: mongoid_test
      hosts:
        - localhost:27017