defaults:
  log_level: INFO
  async_queue: backbeat_server
  log: ~
  client_timeout: 172800
  require_auth_token: false
  alerts:
    email_to: ~
    email_from: ~
  schedules:
    heal_nodes: '0 */2 * * * *'
    daily_activity: '0 12 * * * *'
    log_queues: '0 */5 * * * *'
  reporting:
    intervals: ~
